name: "n8n-ha-addon V2"
version: "2.0.15"
slug: "n8n-ha-addon"
description: "Lance une instance de n8n pour l'automatisation des workflows"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  5678/tcp: 5678
ports_description:
  5678/tcp: "Port pour accéder à l'interface web de n8n"
map:
  - config:rw
  - n8n_data:rw
url: "https://github.com/echavet/n8n_ha_addon"
startup: "application"
boot: "auto"
host_network: true
options:
  webhook_url: "http://localhost:5678"
  env:
    - "N8N_LOG_LEVEL=debug"
    - "N8N_PORT=5678"
schema:
  webhook_url: str
  env:
    - str?